spring:
    datasource:
      driver-class-name: org.h2.Driver
      schema: classpath:db/schema.sql
      data: classpath:db/data.sql
      url: jdbc:h2:mem:test
      username: root
      password: root